### ISSUE TITLE
[BUG] Crash on GetNextSongToPlay()

### ISSUE THREAD

**Issue by Founntain** [Founntain/osuplayer#163]
Error report from tian#6539 on discord. 
Sadly we don't have the information yet, what he/she exactly did to cause this error. However I asked that person to provide us some details so we can reproduce this issue!

```
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List1.get_Item(Int32 index)
   at OsuPlayer.Modules.Audio.Player.GetNextSongToPlay(IList1 songSource, Int32 currentIndex, PlayDirection playDirection) in D:\a\osuplayer\osuplayer\OsuPlayer\Modules\Audio\Player.cs:line 344
   at OsuPlayer.Modules.Audio.Player.NextSong(PlayDirection playDirection) in D:\a\osuplayer\osuplayer\OsuPlayer\Modules\Audio\Player.cs:line 273
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__1280(Object state)
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in //src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in //src/Windows/Avalonia.Win32/Win32Platform.cs:line 283
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in //src/Windows/Avalonia.Win32/Win32Platform.cs:line 217
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in //src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in //src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at OsuPlayer.Program.Main(String[] args) in D:\a\osuplayer\osuplayer\OsuPlayer\Program.cs:line 29
   ```

**Comment by Cesan** [comment]
I added some additional index checks to the play methods. I wonder how this could even happen, because we access the source list with the index received by getting the index of an item in the source list. So this should always be in bounds. The only thing I could imagine is
1. The index returned '-1' for some reason
2. The source list collection changed while playing (unlikely)
