### ISSUE TITLE
[BUG] Crash when logging in with invalid or missing credentials

### ISSUE THREAD

**Issue by pattersonjack** [Founntain/osuplayer#168]
**Describe the bug**

Just something I noticed by misclicking the login button earlier. Specifically, if either the username or password (or both) are empty and the login button is pressed, the player will crash. Also, the same thing happens if you try to log in to a non-existant account.

**To Reproduce**

1. Ensure you are logged out.
2. Enter only one (or none) of the fields required to login to an osu!player account. Or, try to login with invalid credentials.
3. Press the 'login' button.

**Expected behavior**
Probably an error message should be shown indicating the fields are empty, or the login failed.

**Current environment**

OS: Windows 11
Player version: 2022.1202.0

**Here is an example crashlog:**

UTC Time: Wednesday, December 7, 2022 7:27 AM

Error stacktrace below:
Value cannot be null. (Parameter 'owner')
   at Avalonia.Controls.Window.ShowDialog[TResult](Window owner) in /_/src/Avalonia.Controls/Window.cs:line 739
   at Avalonia.Controls.Window.ShowDialog(Window owner) in /_/src/Avalonia.Controls/Window.cs:line 722
   at OsuPlayer.UI_Extensions.MessageBox.ShowDialogAsync(Window window, String text, String title) in D:\a\osuplayer\osuplayer\OsuPlayer\UI Extensions\MessageBox.cs:line 46
   at OsuPlayer.Windows.LoginWindow.Login() in D:\a\osuplayer\osuplayer\OsuPlayer\Windows\LoginWindow.axaml.cs:line 66
   at OsuPlayer.Windows.LoginWindow.LoginBtn_OnClick(Object sender, RoutedEventArgs e) in D:\a\osuplayer\osuplayer\OsuPlayer\Windows\LoginWindow.axaml.cs:line 89
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 283
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at OsuPlayer.Program.Main(String[] args) in D:\a\osuplayer\osuplayer\OsuPlayer\Program.cs:line 29

**Comment by Founntain** [comment]
Thanks for sharing will be checked ASAP.
