### ISSUE TITLE
[BUG] Crashing when loading new background

### ISSUE THREAD

**Issue by wconrad265** [Founntain/osuplayer#186]
A shit, it looks like you did something that the osu!player did not like. If you think this is a bug, please report this crashlog to Founntain by using the buttons below! (Also please don't forget to state how you achieved the crash e. g. what did you do, click etc.)

UTC Time: Sunday, March 26, 2023 12:08 AM

Error stacktrace below:
Could not find a part of the path 'C:\Users\Will\AppData\Local\osu!\Songs\Songs\1493195 sasakureUK - -echo- NieR Song of the Ancients _ Devola ~ Song of the Ancients _ Popola'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at OsuPlayer.IO.DbReader.DataModels.DbMapEntry.FindBackground() in D:\a\osuplayer\osuplayer\OsuPlayer.IO\DbReader\DataModels\DbMapEntry.cs:line 24
   at OsuPlayer.Modules.Audio.Player.TryStartSongAsync(IMapEntryBase song) in D:\a\osuplayer\osuplayer\OsuPlayer\Modules\Audio\Player.cs:line 414
   at OsuPlayer.Modules.Audio.Player.TryPlaySongAsync(IMapEntryBase song, PlayDirection playDirection) in D:\a\osuplayer\osuplayer\OsuPlayer\Modules\Audio\Player.cs:line 311
   at OsuPlayer.Views.SearchView.InputElement_OnDoubleTapped(Object sender, RoutedEventArgs e) in D:\a\osuplayer\osuplayer\OsuPlayer\Views\SearchView.axaml.cs:line 28
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 283
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at OsuPlayer.Program.Main(String[] args) in D:\a\osuplayer\osuplayer\OsuPlayer\Program.cs:line 30

**Comment by Founntain** [comment]
It would be great (as also stated at the top of the message) what you did to get the error. Was your player just playing songs and the crashed. Did it happened after importing etc.

The info is important to reproduce the error. Because if we cant reproduce it we can't help much, because we cant fix it
