### ISSUE TITLE
[BUG] The program suddenly exited.

### ISSUE THREAD

**Issue by Amic72** [Founntain/osuplayer#203]
**I can think of an action that may be related to the issue, which is that I turned on repeat mode for a single track, but I cannot reproduce the problem with this.**
`
Debian GNU/Linux 12 (bookworm) x86_64 
`
Here's what the terminal provided me with:
```
Unhandled exception. System.InvalidOperationException: Call from invalid thread
   at Avalonia.Threading.Dispatcher.VerifyAccess() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 48
   at Avalonia.AvaloniaObject.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 348
   at Avalonia.Visual.set_IsVisible(Boolean value) in /_/src/Avalonia.Visuals/Visual.cs:line 201
   at OsuPlayer.Views.PlaylistViewModel.<>c.<.ctor>b__23_5(MaterialIcon x) in /home/runner/work/osuplayer/osuplayer/OsuPlayer/Views/PlaylistViewModel.cs:line 83
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at OsuPlayer.Views.PlaylistViewModel.<.ctor>b__23_2(ValueChangedEvent`1 d) in /home/runner/work/osuplayer/osuplayer/OsuPlayer/Views/PlaylistViewModel.cs:line 83
   at Nein.Extensions.Bindables.Bindable`1.TriggerValueChanged(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at Nein.Extensions.Bindables.Bindable`1.SetValue(T previous, T value, Boolean bypassChecks, Bindable`1 source)
   at Nein.Extensions.Bindables.Bindable`1.set_Value(T value)
   at OsuPlayer.Modules.Audio.Player.GetNextSongToPlay(IList`1 songSource, Int32 currentIndex, PlayDirection playDirection) in /home/runner/work/osuplayer/osuplayer/OsuPlayer/Modules/Audio/Player.cs:line 362
   at OsuPlayer.Modules.Audio.Player.NextSong(PlayDirection playDirection) in /home/runner/work/osuplayer/osuplayer/OsuPlayer/Modules/Audio/Player.cs:line 284
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
已放弃
```
Additionally, the repeat function seems to be ineffective. Regardless of whether I turn it on or off, the player will select another song after the current one ends, and the repeat mode is automatically turned off.

**Comment by Amic72** [comment]
Here are some of my configurations.
[data.tar.gz](https://github.com/Founntain/osuplayer/files/11551369/data.tar.gz)
